fixes:
  - ".*/Pymacs.py::Pymacs.py.in"
  - "t11_pyfile_works.py::tests/t11_pyfile_works.py.in"
  - "t21_helper_works.py::tests/t21_helper_works.py.in"
  - "t31_elfile_works.py::tests/t31_elfile_works.py.in"
  - "t41_pymacs_works.py::tests/t41_pymacs_works.py.in"
