name: Makefile CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout
      
    - name: Install dependencies
      run: make
      
    - name: Run check
      run: make check
      
